USE master
go
if exists(select name from master..sysdatabases where name='QLBanHangMVC2')
	drop database QLBanHangMVC2
go
create database QLBanHangMVC2
go
use QLBanHangMVC2
go
----2.Tạo bảng, primary key m dung tk win dc k
create table BRAND
(
	BRAND_ID			INT	 			not null ,
	BRAND_NAME			NVARCHAR(100)	NOT NULL,
	BRAND_DESC			NVARCHAR(500)   null 
	constraint PK_BRAND primary key(BRAND_ID)
)
go
create table CATEGORY
(
	CATEGORY_ID		INT			not null,
	CATEGORY_NAME	NVARCHAR(100)		null,
	CATEGORY_DESC	NVARCHAR(500)		null				
	constraint PK_CATEGORY primary key(CATEGORY_ID)
)
go
create table PAYMENT
(
	PAYMENT_ID		    INT				not null,
	PAYMENT_METHOD		NVARCHAR(250)	NOT null,
	PAYMENT_STATUS		NVARCHAR(50)	NOT null,		
	constraint PK_PAYMENT primary key(PAYMENT_ID)
)
go
create table CUSTOMERS
(
	CUSTOMERS_ID	    INT				not null,
	CUSTOMERS_NAME		NVARCHAR(50)	NOT	null,
	CUSTOMERS_PHONE		CHAR(10)		NOT null,
	CUSTOMERS_ADDRESS	NVARCHAR(100)	NOT NULL				
	constraint PK_CUSTOMER primary key(CUSTOMERS_ID)
)
go

create table PRODUCT
(
	PRODUCT_ID			INT				not null,
	CATEGORY_ID			INT				not null,
	BRAND_ID			INT				not null,
	PRODUCT_NAME		NVARCHAR(200)	NOT null,
	PRODUCT_DESC		NVARCHAR(200)	NULL,
	PRODUCT_IMAGE		NVARCHAR(200)	NULL,
	PRODUCT_PRICE		DECIMAL			NOT NULL,
	PRODUCT_STATUS		NVARCHAR(50)	NULL
	constraint PK_PRODUCT primary key(PRODUCT_ID)
)
go
create table ORDERS
(
	ORDERS_ID			INT				not null,
	CUSTOMERS_ID		INT				NOT null,
	PAYMENT_ID			INT				NOT	NULL,
	ORDER_TOTAL			DECIMAL			NOT NULL,
	ORDER_STATUS		NVARCHAR(50)	NOT NULL,
	constraint PK_ORDERS primary key(ORDERS_ID)
)
go
create table ORDER_DETAIL
(
	ORDER_DETAIL_ID				INT				not null,
	ORDERS_ID					INT				not null,
	PRODUCT_ID					INT				not null,
	PRODUCT_NAME				NVARCHAR(200)	NOT null,
	PRODUCT_PRICE				DECIMAL			NOT NULL,
	PRODUCT_SALES_QUANTITY		INT				NOT NULL
	constraint PK_ORDERS_DETAIL primary key(PRODUCT_ID,ORDERS_ID,ORDER_DETAIL_ID)
)
go
----3.Tạo khóa ngoại (foreign key)
ALTER TABLE PRODUCT
	ADD CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
ALTER TABLE PRODUCT
	ADD CONSTRAINT FK_PRODUCT_BRAND FOREIGN KEY(BRAND_ID) REFERENCES BRAND(BRAND_ID)
ALTER TABLE ORDERS
	ADD CONSTRAINT FK_ORDERS_PAYMENT FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
ALTER TABLE ORDERS
	ADD CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY(CUSTOMERS_ID) REFERENCES CUSTOMERS(CUSTOMERS_ID)
ALTER TABLE ORDER_DETAIL
	ADD CONSTRAINT FK_ORDERS_DETAIL_PRODUCT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
ALTER TABLE ORDER_DETAIL
	ADD CONSTRAINT FK_ORDERS_DETAIL_ORDERS FOREIGN KEY(ORDERS_ID) REFERENCES ORDERS(ORDERS_ID)
----4.Nhập dữ liệu
INSERT INTO BRAND VALUES ('01','gIÀY',N'SAAAAAAAAAAAAAAA')